apiVersion: apps/v1
kind: Deployment
metadata:
  name: command
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: command
  template:
    metadata:
      labels:
        app: command
    spec:
      containers:
      - name: command
        image: ghcr.io/heewon00/springboot_cqrs_command_istio:v1
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prd"
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: regsecret
